#!/usr/bin/env bash

source "$(dirname "$0")/_/husky.sh"

if [ "$COMMITIZEN_DISABLE" = "1" ] || [ "${COMMITIZEN_DISABLE,,}" = "true" ]; then
  exit 0
else
  exec < /dev/tty && (npm run commit -- --hook || true)
fi
