name: Release
on:
  push:
    # Branch filter based on the default semantic-release configuration, ref:
    # https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/pre-releases.md#publishing-pre-releases
    # https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches
    branches:
      - master
      - next
      - beta
      - next-major
      - alpha
      # branches named after tags for backports/maintenance
      # TODO: wtf kinda syntax is this
      - '+([0-9])?(.{+([0-9]),x}).x'
  workflow_dispatch:
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - run: yarn install
      - run: yarn test
      # TODO: shareable semantic-release config that lines up with our cz/commitlint ones, ref:
      # https://github.com/semantic-release/semantic-release/blob/master/docs/usage/shareable-configurations.md
      - run: npx --no-install semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
